# Generated by Django 5.0.1 on 2024-01-19 05:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0004_users_alter_book_book_edition'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='mobile',
            field=models.PositiveIntegerField(default='0000000000'),
        ),
        migrations.AlterField(
            model_name='users',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
