# Generated by Django 5.0.1 on 2024-01-19 05:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0005_users_mobile_alter_users_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='mobile',
            field=models.IntegerField(default='0000000000'),
        ),
    ]
