# Generated by Django 5.0.1 on 2024-01-19 08:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0008_alter_users_mobile'),
    ]

    operations = [
        migrations.RenameField(
            model_name='users',
            old_name='email',
            new_name='email_id',
        ),
        migrations.RenameField(
            model_name='users',
            old_name='password',
            new_name='pass_word',
        ),
        migrations.RenameField(
            model_name='users',
            old_name='user_name',
            new_name='username',
        ),
        migrations.RemoveField(
            model_name='users',
            name='mobile',
        ),
    ]
