# Generated by Django 5.0.1 on 2024-01-23 05:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0009_rename_email_users_email_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='users',
            name='c_password',
        ),
    ]
