# Generated by Django 5.0.1 on 2024-01-24 04:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0010_remove_users_c_password'),
    ]

    operations = [
        migrations.CreateModel(
            name='B_issue',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('userId', models.CharField(max_length=20)),
                ('usr_name', models.CharField(max_length=255)),
                ('date_time', models.DateTimeField()),
            ],
        ),
    ]
