# Generated by Django 5.0.1 on 2024-01-24 05:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0011_b_issue'),
    ]

    operations = [
        migrations.RenameField(
            model_name='b_issue',
            old_name='userId',
            new_name='l_Id',
        ),
    ]
