# Generated by Django 5.0.1 on 2024-01-24 05:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0014_alter_b_issue_b_name_alter_b_issue_l_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='b_issue',
            old_name='b_name',
            new_name='b_Id',
        ),
    ]
