# Generated by Django 5.0.1 on 2024-01-24 05:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0015_rename_b_name_b_issue_b_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='b_qty',
            field=models.CharField(default='0', max_length=255),
        ),
    ]
