# Generated by Django 5.0.1 on 2024-01-24 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0017_remove_member_lastname'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='address',
            field=models.CharField(default='0000000000', max_length=255),
        ),
        migrations.AddField(
            model_name='member',
            name='d_o_b',
            field=models.CharField(default='0000000000', max_length=255),
        ),
        migrations.AddField(
            model_name='member',
            name='email',
            field=models.CharField(default='0000000000', max_length=255),
        ),
        migrations.AddField(
            model_name='member',
            name='lastname',
            field=models.CharField(default='0000000000', max_length=255),
        ),
        migrations.AddField(
            model_name='member',
            name='m_type',
            field=models.CharField(default='0000000000', max_length=255),
        ),
        migrations.AddField(
            model_name='member',
            name='mobile',
            field=models.IntegerField(default='0000000000'),
        ),
        migrations.AlterField(
            model_name='member',
            name='firstname',
            field=models.CharField(default='0000000000', max_length=255),
        ),
    ]
