# Generated by Django 5.0.1 on 2024-01-24 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0018_member_address_member_d_o_b_member_email_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='d_o_b',
            field=models.DateField(default='0000/00/00'),
        ),
    ]
