# Generated by Django 5.0.1 on 2024-01-26 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0020_b_issue_r_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='b_issue',
            name='date_time',
            field=models.DateField(),
        ),
    ]
