# Generated by Django 5.0.1 on 2024-01-26 08:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0021_alter_b_issue_date_time'),
    ]

    operations = [
        migrations.RenameField(
            model_name='b_issue',
            old_name='date_time',
            new_name='i_date',
        ),
    ]
