# Generated by Django 5.0.1 on 2024-01-29 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0022_rename_date_time_b_issue_i_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='Login',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('user_name', models.IntegerField(max_length=255)),
            ],
        ),
    ]
