# Generated by Django 5.0.1 on 2024-01-31 02:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0023_login'),
    ]

    operations = [
        migrations.AddField(
            model_name='login',
            name='date_time',
            field=models.TimeField(default='00:00:00'),
        ),
        migrations.AlterField(
            model_name='login',
            name='user_name',
            field=models.CharField(max_length=255),
        ),
    ]
