# Generated by Django 5.0.1 on 2024-01-31 02:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0024_login_date_time_alter_login_user_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='login',
            old_name='date_time',
            new_name='time',
        ),
        migrations.AddField(
            model_name='login',
            name='date',
            field=models.DateField(default='1999-01-01'),
        ),
    ]
