# Generated by Django 5.0.1 on 2024-01-31 02:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0025_rename_date_time_login_time_login_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='login',
            name='date',
        ),
        migrations.RemoveField(
            model_name='login',
            name='time',
        ),
    ]
