# Generated by Django 5.0.1 on 2024-01-31 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0027_users_l_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='l_type',
            field=models.CharField(max_length=255),
        ),
    ]
