# Generated by Django 5.0.1 on 2024-02-01 04:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0029_alter_member_address_alter_users_l_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='d_o_b',
            field=models.CharField(default='YYYY/MM/DD', max_length=250),
        ),
    ]
