# Generated by Django 5.0.1 on 2024-02-05 04:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0033_rename_firstname_b_issue_m_name'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Login',
        ),
        migrations.AddField(
            model_name='book',
            name='b_id',
            field=models.CharField(default='XXXX', max_length=250),
        ),
    ]
