# Generated by Django 5.0.1 on 2024-02-05 04:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0035_remove_book_b_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Issue_requ',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('m_id', models.IntegerField()),
                ('b_id', models.IntegerField()),
                ('req_date', models.CharField(max_length=250)),
                ('issue_date', models.CharField(max_length=250)),
                ('rtrn_date', models.CharField(max_length=250)),
            ],
        ),
    ]
