# Generated by Django 5.0.1 on 2024-02-06 00:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0036_issue_requ'),
    ]

    operations = [
        migrations.CreateModel(
            name='Login_history',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=255)),
                ('user_type', models.CharField(max_length=255)),
                ('date', models.CharField(max_length=255)),
            ],
        ),
        migrations.DeleteModel(
            name='Issue_requ',
        ),
    ]
