# Generated by Django 5.0.1 on 2024-02-07 04:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0038_issued'),
    ]

    operations = [
        migrations.AlterField(
            model_name='issued',
            name='i_date',
            field=models.CharField(default='0000000000', max_length=255),
        ),
        migrations.AlterField(
            model_name='issued',
            name='r_date',
            field=models.CharField(default='0000000000', max_length=255),
        ),
    ]
