# Generated by Django 5.0.1 on 2024-02-08 00:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0040_issued_rqst_date_alter_issued_i_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='issued',
            name='risu_date',
            field=models.DateField(default='1999-01-01'),
        ),
    ]
