# Generated by Django 5.0.1 on 2024-02-08 06:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0043_rturn_i_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rturn',
            name='rqst_date',
        ),
        migrations.RemoveField(
            model_name='rturn',
            name='rtrn_date',
        ),
    ]
