# Generated by Django 5.0.1 on 2024-02-08 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0044_remove_rturn_rqst_date_remove_rturn_rtrn_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rturn',
            name='r_date',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='rturn',
            name='risu_date',
            field=models.DateField(null=True),
        ),
    ]
